spring.application.name=ecommerceapp


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/omnisapp
spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#=================
#Security/JWT
#=================

app.jwt.secret=ThisisASecretKeyForTheSravaniAnnapureddy22
app.jwt.expiration-ms=86400000

#==================
#Twilio
#==================

twilio.account.sid=AC3d6c931f14a8ac53f5abeecdbaa9d899
twilio.auth.token=dccba758cf7036660d823d006d5fe1cb
twilio.phone.number=+16812696814
