spring.application.name=ecommerceapp


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/omnisapp
spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


app.jwt.secret=ThisisASecretKeyForTheSravaniAnnapureddy22
app.jwt.expiration-ms=86400000


